[2022-07-19 03:27:04,793] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: csv_dag.final_dag manual__2022-07-19T03:26:21.274607+00:00 [queued]>
[2022-07-19 03:27:04,805] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: csv_dag.final_dag manual__2022-07-19T03:26:21.274607+00:00 [queued]>
[2022-07-19 03:27:04,806] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-19 03:27:04,806] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-07-19 03:27:04,807] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-19 03:27:04,824] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): final_dag> on 2022-07-19 03:26:21.274607+00:00
[2022-07-19 03:27:04,830] {standard_task_runner.py:52} INFO - Started process 18630 to run task
[2022-07-19 03:27:04,834] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'csv_dag', 'final_dag', 'manual__2022-07-19T03:26:21.274607+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/testDag.py', '--cfg-path', '/tmp/tmpba862dtc', '--error-file', '/tmp/tmppgh5t3u6']
[2022-07-19 03:27:04,836] {standard_task_runner.py:80} INFO - Job 20: Subtask final_dag
[2022-07-19 03:27:04,918] {task_command.py:371} INFO - Running <TaskInstance: csv_dag.final_dag manual__2022-07-19T03:26:21.274607+00:00 [running]> on host 36e1df4dd6ce
[2022-07-19 03:27:05,006] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=csv_dag
AIRFLOW_CTX_TASK_ID=final_dag
AIRFLOW_CTX_EXECUTION_DATE=2022-07-19T03:26:21.274607+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-19T03:26:21.274607+00:00
[2022-07-19 03:27:05,092] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scripts/output_df.py", line 25, in final_df
    index=None, header=True, encoding='utf-8')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 3482, in to_csv
    storage_options=storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/format.py", line 1105, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 243, in save
    storage_options=self.storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
PermissionError: [Errno 13] Permission denied: '/opt/airflow/dags/scripts/data/classic_cars.csv'
[2022-07-19 03:27:05,117] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=csv_dag, task_id=final_dag, execution_date=20220719T032621, start_date=20220719T032704, end_date=20220719T032705
[2022-07-19 03:27:05,137] {standard_task_runner.py:97} ERROR - Failed to execute job 20 for task final_dag ([Errno 13] Permission denied: '/opt/airflow/dags/scripts/data/classic_cars.csv'; 18630)
[2022-07-19 03:27:05,166] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-19 03:27:05,200] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
